ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('<int:product_id>/view/', views.view, name='view'),
    path('<int:product_id>/share/', views.share, name='share'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField()

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    description = models.TextField(blank=True)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = 'img/placeholder.png'
        return url

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse('store:view', kwargs={'product_id': str(self.id)})

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for item in orderitems:
            if item.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    class Meta:
        ordering = ['date_orderd']
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.product)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

    class Meta:
        ordering = ['date_added']
        verbose_name = 'Order item'
        verbose_name_plural = 'Order items'


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.address
    
    class Meta:
        ordering = ['date_added']
        verbose_name = 'Adress'
        verbose_name_plural = 'Adresses'

store/forms.py
from django.forms import Form, CharField, EmailField, TextInput, EmailInput, Textarea

class EmailProductForm(Form):
    name = CharField(max_length=25,
                     widget=TextInput(attrs={
                         'class': 'form-control',
                         'placeholder': 'Enter name',
                     }))
    email = EmailField(widget=EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your email',
    }))
    to = EmailField(widget=EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter email',
    }))
    comments = CharField(required=False, widget=Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Your comments',
    }))

store/views.py
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.http import JsonResponse
from .models import *
from .forms import EmailProductForm
from .utils import cartData, guestOrder
import json
import datetime


def store(request):
    data = cartData(request)
    cartItems = data['cartItems']

    template_name = 'store/store.html'
    products = Product.objects.all()
    context = {'products': products, 'cartItems': cartItems}
    return render(request, template_name, context)


def view(request, product_id):
    data = cartData(request)
    cartItems = data['cartItems']

    product = get_object_or_404(Product, id=product_id)
    context = {'product': product, 'cartItems': cartItems}
    template_name = 'store/view.html'
    return render(request, template_name, context)


def share(request, product_id):
    data = cartData(request)
    cartItems = data['cartItems']

    product = get_object_or_404(Product, id=product_id)
    
    sent = False
    if request.method == 'POST':
        form = EmailProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            product_url = request.build_absolute_uri(product.get_absolute_url())
            subject = f"{cd['name']} recommends you read {product.name}"
            message = f"Read {product.name} at {product_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, cd['email'], [cd['to']])
            sent = True
    else:
        form = EmailProductForm()

    context = {'product': product, 'cartItems': cartItems, 'form': form, 'sent': sent}
    template_name = 'store/share.html'
    return render(request, template_name, context)


def cart(request):
    template_name = 'store/cart.html'

    data = cartData(request)
    cartItems = data['cartItems']
    items = data['items']
    order = data['order']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, template_name, context)


def checkout(request):
    template_name = 'store/checkout.html'

    data = cartData(request)
    cartItems = data['cartItems']
    items = data['items']
    order = data['order']

    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, template_name, context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)
    
    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )
    return JsonResponse('Payment complete', safe=False)

templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a href="{% url 'store:store' %}" class="btn btn-outline-dark">&#x2190; Continue shopping</a>
                <br><br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total: <strong>${{order.get_cart_total|floatformat:2}}</strong></h5></th>
                        <th>
                            <a style="float: right; margin: 5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                        </th>
                    </tr>
                </table>
            </div>
            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex: 2;"></div>
                    <div style="flex: 2;"><strong>Item</strong></div>
                    <div style="flex: 1;"><strong>Price</strong></div>
                    <div style="flex: 1;"><strong>Quantity</strong></div>
                    <div style="flex: 1;"><strong>Total</strong></div>
                </div>
                {% for item in items %}
                <div class="cart-row">
                    <div style="flex: 2;"><img class="row-image" src="{{item.product.imageURL}}" alt="product"></div>
                    <div style="flex: 2;">{{item.product.name}}</div>
                    <div style="flex: 1;">${{item.product.price|floatformat:2}}</div>
                    <div style="flex: 1;">
                        <p class="quantity">{{item.quantity}}</p>
                        <div class="quantity">
                            <img class="chg-quantity update-cart" alt="add item" data-product="{{item.product.id}}" data-action="add" src="{% static  'store/img/arrow-up.png' %}">
				            <img class="chg-quantity update-cart" alt="remove item" data-product="{{item.product.id}}" data-action="remove" src="{% static  'store/img/arrow-down.png' %}">
                        </div>
                    </div>
                    <div style="flex: 1;">${{item.get_total}}</div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    <div id="user-info">
                        <div class="form-field">
							              <input required class="form-control" type="text" name="name" placeholder="Name..">
						            </div>
                        <div class="form-field">
                          <input required class="form-control" type="email" name="email" placeholder="Email..">
                        </div>
                    </div>
                    <div id="shipping-info">
                        <hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
                    </div>
                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
                </form>
            </div>
            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
                <button id="make-payment">Make Payment</button>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="box-element">
                <a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" alt="product image" src="{{item.product.imageURL}}"></div>
                    <div style="flex:2"><p>{{item.product.name}}</p></div>
                    <div style="flex:1"><p>${{item.product.price}}</p></div>
                    <div style="flex:1"><p>x{{item.quantity}}</p></div>
                </div>
                {% endfor %}
                <h5>Items: {{order.get_cart_items}}</h5>
                <h5>Total: ${{order.get_cart_total|floatformat:2}}</h5>
            </div>
        </div>
    </div>

<script type="text/javascript">
  const shipping = '{{order.shipping}}';
  const total = '{{order.get_cart_total}}';

  if (shipping == 'False') {
    document.getElementById('shipping-info').innerHTML = ''
  }

  if (user != 'AnonymousUser') {
    document.getElementById('user-info').innerHTML = ''
  }

  if (shipping == 'False' && user != 'AnonymousUser') {
    document.getElementById('form-wrapper').classList.add('hidden');
    document.getElementById('payment-info').classList.remove('hidden');
  }

  let form = document.getElementById('form');
  form.addEventListener('submit', function(e) {
    e.preventDefault();
    console.log('Form submitted')
    document.getElementById('form-button').classList.add('hidden');
    document.getElementById('payment-info').classList.remove('hidden');
  });

  document.getElementById('make-payment').addEventListener('click', function(e) {
    submitFormData();
  })

  const submitFormData = () => {
    console.log('Payment button clicked');
    const userFormData = {
      'name': null,
      'email': null,
      'total': total,
    }
    const shippingInfo = {
      'address': null,
      'city': null,
      'state': null,
      'zipcode': null,
    }

    if (shipping != 'False') {
      shippingInfo.address = form.address.value;
      shippingInfo.city = form.city.value;
      shippingInfo.state = form.state.value;
      shippingInfo.zipcode = form.zipcode.value;
    }

    if (user == 'AnonymousUser') {
      userFormData.name = form.name.value;
      userFormData.email = form.email.value;
    }

    const url = '/process_order/';
    fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRFToken': csrftoken,
      },
      body: JSON.stringify({
        'form': userFormData,
        'shipping': shippingInfo, 
      })
    })
    .then((res) => res.json())
    .then((data) => {
      console.log('Success', data);
      alert('Transaction completed');
      cart = {};
      document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/";
      window.location.href = "{% url 'store:store' %}";
    });
  }
</script>
{% endblock %}

templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'store/css/main.css' %}">
    <link rel="icon" href="{% static 'store/img/icon.ico' %}">
    <title>{% block title %}Welcome to shop!{% endblock %}</title>
</head>
<body>
    {% include 'store/includes/navbar.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'store/includes/footer.html' %}

    <script text="text/javascript">
      let user = '{{request.user}}'
      const getToken = (name) => {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      const csrftoken = getToken('csrftoken');

      function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    const cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(let i = 0; i < cookieArr.length; i++) {
		        const cookiePair = cookieArr[i].split("=");

		        /* Removing whitespace at the beginning of the cookie name
		        and compare it with the given string */
		        if(name == cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
          }

          // Return null if not found
          return null;
      }
      let cart = JSON.parse(getCookie('cart'))

      if (!cart){
        cart = {}
        document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
      }
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="{% static 'store/js/cart.js' %}" text="text/javascript"></script>
</body>
</html>

templates/store/share.html
{% extends 'store/main.html' %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ product.name }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
    <div class="container">
        <h1>Share "{{ product.name }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Send e-mail</button>
        </form>
    </div>
    {% endif %}
{% endblock %}

templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4">
            <img class="thumbnail" src="{{product.imageURL}}" alt="">
            <div class="box-element product">
                <h6><strong>{{product.name}}</strong></h6>
                <hr>
                <button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                <a class="btn btn-outline-success" href="{% url 'store:view' product.id %}">View</a>
                <h4 style="display: inline-block; float: right">${{product.price|floatformat:2}}</h4>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/store/view.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}{{product.name}}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <ul class="list-group">
                            <li class="list-group-item"><h1>{{product.name}}</h1></li>
                            <li class="list-group-item"><h2>{{product.price|floatformat:2}} $</h2></li>
                            <li class="list-group-item"><h4>
                                {% if product.description %}
                                    {{product.description}}
                                {% else %}
                                    Description is empty
                                {% endif %}
                            </h4></li>
                            <li class="list-group-item"><h4>Digital: {{product.digital}}</h4></li>
                            <li class="list-group-item">
                                <button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                                <a class="btn btn-outline-info add-btn update-cart" href="{% url 'store:share' product.id %}" role="button">Share with Email</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm">
                        <img class="img-thumbnail" src="{{product.imageURL}}" alt="product image">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}